# Generated by Django 5.0.4 on 2024-04-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('paswd', models.CharField(max_length=200)),
                ('estad', models.CharField(max_length=200)),
            ],
        ),
    ]
